modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]] 
modId="itprojekt" 
version="${file.jarVersion}" 
displayName="IT Projekt" 
logoFile="logo.png" 
authors="DanyGames2014 (Daniel Fildán)" 
description='''
IT Projekt

Minecraft Mod
'''

[[dependencies.itprojekt]] 
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.itprojekt]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
